import { NextResponse } from "next/server";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { sqlClient } from "@/lib/db/client";

const input = z.object({ amountOre: z.coerce.number().int().positive(), paidAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), note: z.string().trim().max(500).optional() });

export async function GET(_request: Request, ctx: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const { id } = await ctx.params; const payments = await sqlClient`SELECT p.* FROM invoice_payments p JOIN invoices i ON i.id=p.invoice_id WHERE p.invoice_id=${id} AND i.organization_id=${user.organizationId} ORDER BY p.paid_at DESC`; return NextResponse.json({ payments }); } catch { return NextResponse.json({ error: "Ikke innlogget." }, { status: 401 }); } }

export async function POST(request: Request, ctx: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const { id } = await ctx.params; const parsed = input.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Kontroller beløp og betalingsdato." }, { status: 400 }); const invoice = await sqlClient.begin(async (tx) => { const rows = await tx`SELECT * FROM invoices WHERE id=${id} AND organization_id=${user.organizationId} FOR UPDATE`; const current = rows[0]; if (!current) return null; if (["DRAFT", "VOID"].includes(current.status)) throw new Error("INVALID_STATUS"); await tx`INSERT INTO invoice_payments (organization_id, invoice_id, amount_ore, paid_at, source, note, created_by) VALUES (${user.organizationId}, ${id}, ${parsed.data.amountOre}, ${new Date(parsed.data.paidAt + "T12:00:00Z")}, 'MANUAL', ${parsed.data.note || null}, ${user.id})`; const sums = await tx`SELECT COALESCE(sum(amount_ore),0)::bigint AS paid FROM invoice_payments WHERE invoice_id=${id}`; const paid = Number(sums[0].paid), remaining = Math.max(0, Number(current.total_ore) - paid); const status = remaining === 0 ? "PAID" : "PARTIALLY_PAID"; const updated = await tx`UPDATE invoices SET paid_amount_ore=${paid}, remaining_amount_ore=${remaining}, status=${status}, paid_at=${remaining === 0 ? new Date() : null}, updated_at=now() WHERE id=${id} RETURNING *`; if (!remaining) await tx`UPDATE orders SET status='CLOSED', closed_at=now(), updated_at=now() WHERE id=${current.source_order_id}`; return updated[0]; }); if (!invoice) return NextResponse.json({ error: "Fakturaen finnes ikke." }, { status: 404 }); return NextResponse.json({ invoice }); } catch (error) { if (error instanceof Error && error.message === "INVALID_STATUS") return NextResponse.json({ error: "Fakturaen må være finalisert først." }, { status: 409 }); return NextResponse.json({ error: "Kunne ikke registrere betalingen." }, { status: 500 }); } }
