import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db/client";
import { customers, orders, organizations, organizationSettings } from "@/lib/db/schema";

const schema = z.object({ origin: z.string().trim().min(3), destination: z.string().trim().min(3), emissionType: z.enum(["GASOLINE", "DIESEL", "HYBRID", "ELECTRIC"]).default("GASOLINE") });
async function context(id: string, organizationId: string) { const [row] = await db.select({ order: orders, customer: customers }).from(orders).innerJoin(customers, eq(customers.id, orders.customerId)).where(and(eq(orders.id, id), eq(orders.organizationId, organizationId))).limit(1); const [[org], [settings]] = await Promise.all([db.select().from(organizations).where(eq(organizations.id, organizationId)).limit(1), db.select().from(organizationSettings).where(eq(organizationSettings.organizationId, organizationId)).limit(1)]); return { row, org, settings }; }
const address = (value: { address?: string | null; postalCode?: string | null; city?: string | null }) => [value.address, value.postalCode, value.city].filter(Boolean).join(", ");

export async function GET(_request: Request, ctx: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const { id } = await ctx.params; const data = await context(id, user.organizationId); if (!data.row) return NextResponse.json({ error: "Ordren finnes ikke." }, { status: 404 }); return NextResponse.json({ origin: address(data.org ?? {}), destination: data.row.order.workAddress || address(data.row.customer), mileageRateOre: data.settings?.mileageRateOre ?? 500, mapsConfigured: Boolean(process.env.GOOGLE_MAPS_API_KEY) }); } catch { return NextResponse.json({ error: "Ikke innlogget." }, { status: 401 }); } }

export async function POST(request: Request, ctx: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const { id } = await ctx.params; const data = await context(id, user.organizationId); if (!data.row) return NextResponse.json({ error: "Ordren finnes ikke." }, { status: 404 }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Kontroller adressene." }, { status: 400 }); const key = process.env.GOOGLE_MAPS_API_KEY; if (!key) return NextResponse.json({ error: "Google Maps er ikke aktivert ennå.", mapsConfigured: false }, { status: 503 }); const response = await fetch("https://routes.googleapis.com/directions/v2:computeRoutes", { method: "POST", headers: { "content-type": "application/json", "X-Goog-Api-Key": key, "X-Goog-FieldMask": "routes.distanceMeters,routes.duration,routes.travelAdvisory.tollInfo" }, body: JSON.stringify({ origin: { address: parsed.data.origin }, destination: { address: parsed.data.destination }, travelMode: "DRIVE", languageCode: "nb-NO", units: "METRIC", extraComputations: ["TOLLS"], routeModifiers: { vehicleInfo: { emissionType: parsed.data.emissionType } } }) }); const value = await response.json(); if (!response.ok || !value.routes?.[0]) return NextResponse.json({ error: "Google fant ingen kjørerute mellom adressene." }, { status: 422 }); const route = value.routes[0]; const price = route.travelAdvisory?.tollInfo?.estimatedPrice?.find((item: { currencyCode?: string }) => item.currencyCode === "NOK"); const tollOre = price ? Number(price.units ?? 0) * 100 + Math.round(Number(price.nanos ?? 0) / 10_000_000) : 0; return NextResponse.json({ distanceKm: Math.round(route.distanceMeters / 100) / 10, duration: route.duration, tollOre, tollKnown: Boolean(price) }); } catch { return NextResponse.json({ error: "Kunne ikke beregne ruten." }, { status: 500 }); } }
